# This pipeline builds Linux, macOS, and Windows executables.
# A Github release is created, the CHANGELOG.md rotated, and the QtonSolutions/homebrew-tap update with the new build.
# The build artifacts are not shared between the build machines so other actions are run on specific machines. These
# are commented in those parts of the pipeline definition.

# Only build tags
if: tag IS present

env:
  global:
    # Contains:
    # - GH_TOKEN: Personal access token required for publishing releases, making commits in other repos. Only public
    #             repo access required
    secure: UsAMM8dliojkviCbS5ei7/TcgalEBw1eHbIWMCbsFyK80CcBrQEDR1rkFucsQ9ZSCjx04q33/A1/ghi2yDhZKBqE7mQYrB5UYo6FYbxpvv1Gbc45GBKhVmi1Zna15+hU/8Ob1KqAQOFiRYrZaB+AVpZwUsrpK2WR6hTbZlb3WeANMm1EhN8zxeN5dc+DVbWZp/sHank8CHOvjF0xPsv+C+eOKeXizuzkyKsD4CzLGri4IsQiRxd/0EoAXELnVzfifKJqrFBbOfJu/7EeFduiSfl+kpxbDDJv3gB4vKgrE4ML/PP7kvzV276OQW9tULcfErUJQAAX6bpXYFuXBt35wvppYycbURmSoUaoHbD4Ldcx66Za45cMDaA4gYRtcb9BVJd85Gzw8A6lU898JxnEQaUKO4rcXxhctgjGP2WAoJaQZ4pdYhe68LRnCu2s9ngqSUEMUHjrAC3rkRPQC76r47s8GzrMC+9LSSKfYUi+mA0FwBvVY7THfW+d5SXVAevmMIaQw4GOMxztAYr0LF9akeU0pwJtRB2inz1u+R0WwDO+d2YAa83i12PeKnIa0KMCc6HGFCXH2WH8J2jHOhK8I2YHHxzpWP7WP2c9dgUv+nO8V+R+1sFB/+UCfrtyAMDUAz6e2g9reIeGPc4Pzw2SRhcLnFsPYZAze8pGTNY8Gf8=

# Required to allow updating CHANGELOG.md after a build
git:
  depth: false

language: python
cache: pip
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows
script: python3 scripts/release.py ${TRAVIS_BRANCH} || python scripts/release.py ${TRAVIS_BRANCH}
matrix:
  include:
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8
      before_deploy:
        # Compress the executable so it can be added to the Github release
        - gzip -c dist/sessh > dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.gz
        # Create a release notes file with all the unreleased changes so it can be used for the Github release
        - python scripts/create_release_notes.py ./CHANGELOG.md ./release_notes.md
      deploy: &deploy_base
        provider: releases
        skip_cleanup: true
        # From env.global.secure
        api_key: ${GH_TOKEN}
        file_glob: true
        file: dist/sessh-*.gz
        draft: false
        # Use travis-ci/dpl for releases because it has more features
        edge: true
        name: ${TRAVIS_BRANCH}
        release_notes_file: "./release_notes.md"
        on:
          all_branches: false
          tags: true
      after_script:
        # Update the CHANGELOG.md to make all the [Unreleasd] notes part of this release and create a new [Unreleased]
        # section. This should only be done once per build so pick the Linux machine because it normally finishes first.
        - python scripts/create_next_release_in_changelog.py ./CHANGELOG.md ${TRAVIS_BRANCH}
    # Python 3.8 is keg-only in Homebrew so it's a pain to update the paths to make it the default `python3`.
    # 3.7.x should be fine until this changes.
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.3
      language: shell
      # Compress the executable so it can be added to the Github release
      before_deploy: python3 --version && gzip -c dist/sessh > dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.gz
      deploy:
        <<: *deploy_base
        # Use the regular (non travis-ci/dpl) release mechanism to avoid some strange errors.
        edge: false
      # Update the QtonSolutions/homebrew-tap sessh formula with the new build information.
      after_deploy: python3 scripts/publish_release_to_homebrew_tap.py "${TRAVIS_BRANCH}" "dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.gz"
    - name: "Python 3.8.2 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install 7zip.portable
        # Pin to 3.8.2 because the env paths will need updating once 3.9 becomes stable and I can't see how to install
        # any 3.8.x version.
        - choco install python --version 3.8.2
        - python -m pip install --upgrade pip
      # Compress the executable so it can be added to the Github release
      before_deploy: 7za.exe a -tzip dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.zip dist/sessh.exe
      deploy:
        <<: *deploy_base
        file: dist/sessh-*.zip
        # travis-ci/dpl doesn't seem to work on Windows at the moment
        edge: false
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
