if: tag IS present

env:
  global:
    secure: OwYJV9hxuwJ0O2tnbzjQdgfu9h6MiCaeBgkiwuExU7drYsckQXdQQ49m9YpXd5Aj1poaTNbC24t23UxUaFqE+ST4loScEhxwvM6CipjkSRf7Fs91jdhqOcjgO7Rw37J3WIAxuIy/7SYX0zfmf1rLKaoz+mY1Bld2cbTZytXvONXOMJj4Btoq8zAWLBT5sybHJBztiiYRE8l/gR1CyYuw5SL/kLBK0VIHACtF+H7olELksUf/gnPktbJXgDz3XZbvbOTY/pcymPsHxmJXKIjik7kX0s0SXkWtKFGPo7gcjsNpE0oxUCmAwy6DaTeTumUuOW4GqrJwTPBqtu946Qe2Ubx+QBMevJk6Y6KmRip9pkZNO09/qyVkC4BJ3KTA8pW6VAwtaw11yO58/dwHmQKPGRGEzkozEJvGKk8wXx7wBvlRLdtwP84SvqGhkxkFS8BRCw6MbYVIHdxkrJBUG+/wXjej3UU/7xIvWIXvp65HYo46UUxnMtvksH3+vwabrFqH4YhKZS5Ru0+R8lzaY0xMbvLBkWan9Ps3/vaXMGkddTN8fukeWL0Vt83399J95+s0k1xxi0DitywwaId60MPDxzPxb4vaMbHxD6mgDsmKsp2KMdPCQC5aUSPUXhJdOqKtY6syqWswqhGa2YPOiy9cIZJqwsF+Uovqc7l8Rmynv3Y=

# Required to allow updating CHANGELOG.md after a build
git:
  depth: false

language: python
cache: pip
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install -r requirements.txt
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 scripts/release.py || python scripts/release.py
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      before_deploy:
        - gzip -c dist/sessh > dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.gz
        - python3 scripts/create_release_notes.py ./CHANGELOG.md ./release_notes.md || python scripts/create_release_notes.py ./CHANGELOG.md ./release_notes.md
      deploy: &deploy_base
        provider: releases
        skip_cleanup: true
        # From env.global.secure
        api_key: ${GH_TOKEN}
        file_glob: true
        file:
          - dist/sessh-*
        draft: false
        edge:
          # https://github.com/travis-ci/dpl/issues/1102
          branch: master
        name: ${TRAVIS_BRANCH}
        release_notes_file: "./release_notes.md"
        on:
          all_branches: false
          tags: true
      # This should only be done once per build so pick the Linux machine because it normally finishes first
      after_script:
        - git config credential.helper "store --file=.git/credentials"
        - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
        - git config --local user.name "Travis CI"
        - git config --local user.email "noreply@sms-plc.com"
        - python3 scripts/create_next_release_in_changelog.py ./CHANGELOG.md ${TRAVIS_BRANCH} || python scripts/create_next_release_in_changelog.py ./CHANGELOG.md ${TRAVIS_BRANCH}
        - git checkout develop
        - git add CHANGELOG.md
        - git commit -m "Update CHANGELOG.md after building ${TRAVIS_BRANCH}"
        - git push
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_deploy:
        - gzip -c dist/sessh > dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.gz
        - python3 scripts/create_release_notes.py ./CHANGELOG.md ./release_notes.md || python scripts/create_release_notes.py ./CHANGELOG.md ./release_notes.md
      deploy:
        <<: *deploy_base
#    - name: "Python 3.7.4 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python
#        - python -m pip install --upgrade pip
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
