language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
#    - name: "Python 3.7.4 on macOS"
#      os: osx
#      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
#      language: shell       # 'language: python' is an error on Travis CI macOS
#    - name: "Python 3.7.4 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python
#        - python -m pip install --upgrade pip
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install -r requirements.txt
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 scripts/release.py || python scripts/release.py
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: RDjNxhGNUUiZZhuTItsrdF48h3Hc+fT3xD58b7+H6P8bCJLeM3GFnTVeMX4xqZ2nr4bMV79mMj/HhBy8pmlSieS6zTnYmNB7rHuO/ZPJiKbgzUhxs6QUWAPFPQJ6gv8LBeP+SVgEnpa2jdGw8WE2lijw5TvdDMh1YgrF02chZkdnXD8I8QC+ZHCLroa5XCqa5FE44aMPdj6Mx52VV1UWLqqV/l1w/wy/wfOhyfuNzKxRLnqtYPnwJeSuP2GDLjoWSedoZGDVxkN91unzlNeqHMLvTHrt6H7kqnBifxq8aZu2VXMx1wSqUqAhKc35H7L6yQI9d7IUBtLCZkPexskEBN0MmzvWmKDyDKnv372ZzrKzJHR2og+cHGdAVFZdwTTxHJrPZm9PIAa20RC5hAb62FuVTtEUXZonyL++2R+I9QFTJHvhmpssblgwxnRRJhUb8iRSF+X5NnBks1Ru0RkGc8ikUJjCb7caEVEaAvDOyEMgBI3Osm0An46h16Y+c5sQiMpZT5Fvyit7J1idIPx8ulD55r1p8C+FjG1pggJBC1Sgh9biCUaUSSNOUWvk+j2rxW/OgtVjJ41NrQKdjsUqw6msZYeZqJ7C9/REQ+Bg5GVvjIiilK/14SkV5K52xGgkS9QdzfFikmhPB3IIBkc6IBfl7crSVuoS/I5F7IO3Mck=
  file_glob: true
  file: dist/*
  draft: true
  on:
    all_branches: true
    tags: false
