# This pipeline builds Linux, macOS, and Windows executables.
# A Github release is created, the CHANGELOG.md rotated, and the QtonSolutions/homebrew-tap update with the new build.
# The build artifacts are not shared between the build machines so other actions are run on specific machines. These
# are commented in those parts of the pipeline definition.

# Only build tags
if: tag IS present

env:
  global:
    # Contains:
    # - GH_TOKEN: Personal access token required for publishing releases, making commits in other repos. Only public
    #             repo access required
    secure: OwYJV9hxuwJ0O2tnbzjQdgfu9h6MiCaeBgkiwuExU7drYsckQXdQQ49m9YpXd5Aj1poaTNbC24t23UxUaFqE+ST4loScEhxwvM6CipjkSRf7Fs91jdhqOcjgO7Rw37J3WIAxuIy/7SYX0zfmf1rLKaoz+mY1Bld2cbTZytXvONXOMJj4Btoq8zAWLBT5sybHJBztiiYRE8l/gR1CyYuw5SL/kLBK0VIHACtF+H7olELksUf/gnPktbJXgDz3XZbvbOTY/pcymPsHxmJXKIjik7kX0s0SXkWtKFGPo7gcjsNpE0oxUCmAwy6DaTeTumUuOW4GqrJwTPBqtu946Qe2Ubx+QBMevJk6Y6KmRip9pkZNO09/qyVkC4BJ3KTA8pW6VAwtaw11yO58/dwHmQKPGRGEzkozEJvGKk8wXx7wBvlRLdtwP84SvqGhkxkFS8BRCw6MbYVIHdxkrJBUG+/wXjej3UU/7xIvWIXvp65HYo46UUxnMtvksH3+vwabrFqH4YhKZS5Ru0+R8lzaY0xMbvLBkWan9Ps3/vaXMGkddTN8fukeWL0Vt83399J95+s0k1xxi0DitywwaId60MPDxzPxb4vaMbHxD6mgDsmKsp2KMdPCQC5aUSPUXhJdOqKtY6syqWswqhGa2YPOiy9cIZJqwsF+Uovqc7l8Rmynv3Y=

# Required to allow updating CHANGELOG.md after a build
git:
  depth: false

language: python
cache: pip
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows
script: python3 scripts/release.py ${TRAVIS_BRANCH} || python scripts/release.py ${TRAVIS_BRANCH}
matrix:
  include:
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8
      before_deploy:
        # Compress the executable so it can be added to the Github release
        - gzip -c dist/sessh > dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.gz
        # Create a release notes file with all the unreleased changes so it can be used for the Github release
        - python scripts/create_release_notes.py ./CHANGELOG.md ./release_notes.md
      deploy: &deploy_base
        provider: releases
        skip_cleanup: true
        # From env.global.secure
        api_key: ${GH_TOKEN}
        file_glob: true
        file: dist/sessh-*.gz
        draft: false
        # Use travis-ci/dpl for releases because it has more features
        edge: true
        name: ${TRAVIS_BRANCH}
        release_notes_file: "./release_notes.md"
        on:
          all_branches: false
          tags: true
      after_script:
        # Update the CHANGELOG.md to make all the [Unreleasd] notes part of this release and create a new [Unreleased]
        # section. This should only be done once per build so pick the Linux machine because it normally finishes first.
        - python scripts/create_next_release_in_changelog.py ./CHANGELOG.md ${TRAVIS_BRANCH}
    # Python 3.8 is keg-only in Homebrew so it's a pain to update the paths to make it the default `python3`.
    # 3.7.x should be fine until this changes.
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.3
      language: shell
      # Compress the executable so it can be added to the Github release
      before_deploy: python3 --version && gzip -c dist/sessh > dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.gz
      deploy:
        <<: *deploy_base
        # Use the regular (non travis-ci/dpl) release mechanism to avoid some strange errors.
        edge: false
      # Update the QtonSolutions/homebrew-tap sessh formula with the new build information.
      after_deploy: python3 scripts/publish_release_to_homebrew_tap.py "${TRAVIS_BRANCH}" "dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.gz"
    - name: "Python 3.8.2 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install 7zip.portable
        # Pin to 3.8.2 because the env paths will need updating once 3.9 becomes stable and I can't see how to install
        # any 3.8.x version.
        - choco install python --version 3.8.2
        - python -m pip install --upgrade pip
      # Compress the executable so it can be added to the Github release
      before_deploy: 7za.exe a -tzip dist/sessh-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}.zip dist/sessh.exe
      deploy:
        <<: *deploy_base
        file: dist/sessh-*.zip
        # travis-ci/dpl doesn't seem to work on Windows at the moment
        edge: false
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
